README.md, drupal/.lando.yml, drupal/.lando/generate_oauth_keys.sh, drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_next_setup/config/next.next_entity_type_config.node.article.yml, drupal/recipes/wunder_next_setup/config/next.next_site.next_js_localhost.yml, drupal/recipes/wunder_next_setup/config/simple_oauth.settings.yml, drupal/recipes/wunder_next_setup/config/user.role.next_api_role.yml, drupal/recipes/wunder_next_setup/recipe.yml, drupal/web/modules/custom/wunder_next/composer.json, drupal/web/modules/custom/wunder_next/drush.services.yml, drupal/web/modules/custom/wunder_next/src/Commands/WunderNextCommands.php, drupal/web/modules/custom/wunder_next/wunder_next.info.yml, next/.env.example, next/lib/drupal.ts
This branch adds instructions and automation to set up preview mode when kicking off a project using this starter, using a combination of a drupal recipe and a custom module that provides a drush command to set some parts up.
Following the instructions[ on the next-drupal website](https://next-drupal.org/learn/preview-mode), these are the steps needed: 
1. https://next-drupal.org/learn/preview-mode/create-site > added the site entity to the recipe
2. https://next-drupal.org/learn/preview-mode/create-oauth-client
* role with permission -> added role and permissions to the recipe
* key generation -> added lando script that generates the keys in the correct directory
* creation of a user and the consumer connected to that user -> added a custom module with a drush command that creates the …
=> NEX-16: add preview to the mostly automated setup of the project locally

drupal/.lando.yml, drupal/web/modules/custom/wunder_next/wunder_next.module, drupal/web/sites/default/settings.php
* added the env var to lando setup WUNDER_NEXT_FRONTEND_URL
* added setting to settings.php using the env var
* added implementation of hook_ENTITY_TYPE_load to set the value dynamically based on the setting
This implies that there's only one frontend site (but for the standard case that should be ok), and also that there's a frontend site with the id "frontend", but we are creating that as part of the recipe, so we can be confident that it's there.
=> NEX-19: Add mechanism to make the frontend url in drupal tied to an env var

.lando.yml, README.md, drupal/recipes/wunder_next_setup/config/next.next_entity_type_config.node.article.yml, drupal/recipes/wunder_next_setup/config/next.next_entity_type_config.node.landing_page.yml, drupal/recipes/wunder_next_setup/config/next.next_entity_type_config.node.page.yml, drupal/web/modules/custom/wunder_next/wunder_next.module, drupal/web/sites/default/settings.php, next/pages/[...slug].tsx, next/pages/api/revalidate.ts, next/pages/index.tsx
*Link to ticket: [NEX-26](https://wunder.atlassian.net/browse/NEX-26)*
This PR adds [incremental static regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) and [On demand revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation) to our setup.
To make this work, this PR adds: 
* revalidate property for the index and slug pages
* telling drupal to use the lando proxied path for frontend "https://frontend.lndo.site" instead of the localhost:3000  (so this the url that will be used for revalidation and also for iframes inside the site
* adding the new env var "DRUPAL_REVALIDATE_SECRET"
* setting content types's property for revalidation
This mechanism is pretty rudimentary compared …
=> NEX-26: Add revalidation feature

drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_next_setup/config/redirect.settings.yml, drupal/recipes/wunder_next_setup/recipe.yml, next/pages/[...slug].tsx
Support for redirects with multilingual setups seem to be a problematic area for this setup. I have written a message in the official slack: https://drupal.slack.com/archives/C01E36BMU72/p1671781046005709 
This PR adds partial support for redirects, with these limitations:
1. redirects need to be created manually, we cannot use the "Automatically create redirects when URL aliases are changed." `/admin/config/search/redirect/settings`, so that is disabled in the recipe
2. no redirects to external urls (https://www.drupal.org/project/decoupled_router/issues/3133681 old patch, won't apply)
3.  English redirects (or default language redirects) need to be marked for all languages
4.  language specific redirects need to be marked for that language
*Link to ticket: …
=> NEX-31: Add partial support for redirects

next/components/locale-switcher.tsx
When I tried to run `lando npm run build`, while on the main branch,  the command failed with: 
```
Failed to compile.
./components/locale-switcher.tsx
13:19  Error: Insert `;`  prettier/prettier
14:4  Error: Insert `;`  prettier/prettier
19:24  Error: Insert `;`  prettier/prettier
21:4  Error: Insert `;`  prettier/prettier
24:32  Error: Replace `(locale·=>·locale·!=·language))` with `((locale)·=>·locale·!=·language));`  prettier/prettier
25:6  Warning: React Hook useEffect has a missing dependency: 'locales'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
25:17  Error: Replace `⏎` with `;`  prettier/prettier
35:72  Error: Insert `}·pr-3`}>`  prettier/prettier
36:11  Error: Replace `}·pr-3`}>{languageLinks[language]?.name}` with …
```
=> NEX-30: Language switcher fixes

drupal/composer.json
I have added a new version of the patch on d.org: https://www.drupal.org/project/jsonapi_menu_items/issues/3192576#comment-14914978
This should add back the langcode when getting menu items from jsonapi.
To test
1. delete the web/modules/custom folder
2. run `lando composer install` so the patch is applied
3. test the response of menus
=> Add back a patch for the jsonapi_menu_items module that adds the langcode

drupal/composer.json
There's now a more updated version of the patch to get filtering for menu items from d.org . Seems to be better than what I made, so let's move to that one :-)
To test, run the whole thing again and verify that menus appear only if in the appropriate language
=> Update the patch for json_api_menu_items

drupal/recipes/wunder_landing_pages/README.md, drupal/recipes/wunder_landing_pages/config/core.base_field_override.node.frontpage.promote.yml, drupal/recipes/wunder_landing_pages/config/core.entity_form_display.node.frontpage.default.yml, drupal/recipes/wunder_landing_pages/config/core.entity_view_display.node.frontpage.default.yml, drupal/recipes/wunder_landing_pages/config/core.entity_view_display.node.frontpage.teaser.yml, drupal/recipes/wunder_landing_pages/config/field.field.node.frontpage.field_content_elements.yml, drupal/recipes/wunder_landing_pages/config/language.content_settings.node.frontpage.yml, drupal/recipes/wunder_landing_pages/config/node.type.frontpage.yml, drupal/recipes/wunder_landing_pages/config/pathauto.pattern.frontpage.yml, drupal/recipes/wunder_next_setup/config/next.next_entity_type_config.node.frontpage.yml, drupal/web/modules/custom/wunder_next/src/Plugin/Validation/Constraint/UniqueFrontpage.php, drupal/web/modules/custom/wunder_next/src/Plugin/Validation/Constraint/UniqueFrontpageValidator.php, drupal/web/modules/custom/wunder_next/wunder_next.module, drupal/web/modules/custom/wunder_search/src/Plugin/ElasticsearchIndex/MultilingualContentIndex.php, drupal/web/modules/custom/wunder_search/src/Plugin/Normalizer/NodeNormalizer.php, next/components/node--frontpage.tsx, next/lib/get-params.ts, next/pages/[...slug].tsx, next/pages/index.tsx
This branch adds the possibility for the content editor to decide what is displayed on the frontpage of the site for each of the translations.
In the backend: 
* there is now a new content type called "frontpage". Paragraphs can be added to the frontpage and it can be translated
* there is a constraint that prevents editors to add more than one frontpage translation per language
* the path of the frontpage is set via pathauto
* the frontend node is not indexed in elasticsearch (this PR also fixes an issue where items could not be deleted from elasticsearch)
On the frontend:
* the `index.tsx` contains a query to get the frontpage for the language. if found, its contents (paragraphs) are rendered at the top of the page, before the fixed listing that shows the latest articles.
* because the …
=> NEX-39: Add frontpage handling

next/components/article.tsx, next/lib/get-node-page-json-api-params.ts, next/lib/zod/article-teaser.ts, next/lib/zod/article.ts
This PR shows field_excerpt on article pages. It does NOT add it to the article "teaser" list on the frontpage.
To test, run the usual `lando npm run dev` and navigate to an article page - you should see the excerpt if available.
=> Show excerpt on article pages

next/components/paragraph--links.tsx
Implements https://wunder.atlassian.net/browse/NEX-47
This PR adds some basic styling to the links paragraphs so they're a bit more useful as an example. There wasn't anything similar in the component library, so I made something up. I probably won't win any design awards anytime soon :)
=> NEX-47: Style links paragraph

next/components/paragraph.tsx
https://wunder.atlassian.net/browse/NEX-46
This PR adds and example of using [Next.js Dynamic Imports](https://nextjs.org/docs/advanced-features/dynamic-import) to defer loading of the ParagraphAccordion and ParagraphVideo components until they're needed. It does seem to to have a (modest) effect - the "First load JS" on the homepage is 6kB less on the homepage where neither component is used. For this template, though, it's more about introducing the pattern, so developers are aware that this is the way to prevent the Paragraph component growing over time.
`next build` before and after:
=> NEX-46: Dynamically import Accordion and Video paragraphs

.circleci/config.yml, silta/silta-next.yml, silta/silta.yml
Compared to the existing `siltatest` branch, this branch adds:
* postupgrade command that executes the same steps that we instruct users to run locally in lando
* added (hardcoded) env vars needed for the drush command that creates the consumer in drupal
1. when the migration creates the content, the backend site will try to contact the frontend site to invalidate the pages: this will result in errors, but they can be ignored
2. drupal's admin password shows up in the output in circleci, which is public for this project, maybe not great?
Other than those, I think this can serve the needs of the template, so we can be sure that the whole mechanism works at each commit.
=> Silta: install the site at each deployments

drupal/composer.lock
This PR updates the next-drupal module to https://www.drupal.org/project/next/releases/1.6.3
=> NEX-57: Update next-drupal to version 1.6.3

drupal/recipes/wunder_base/config/node.type.article.yml, drupal/recipes/wunder_pages/config/node.type.page.yml
Jira: https://wunder.atlassian.net/browse/NEX-61
This PR hides the standard Drupal "preview" buttons in all existing content types, to prevent confusion with the next.js preview.
=> NEX-61: Do not show preview buttons in content types edit form

.circleci/config.yml
- Use silta-cli release name command instead of custom logic to get the correct environment domains
*How to test:*
1. Check the site works
*Link to feature environment:*
Drupal: feature-support-long-branch-nacf7.next4drupal-project.dev.wdr.io
Frontend: feature-support-long-branch-na7b0.next4drupal-project.dev.wdr.io
=> Replace release name logic with silta cli command.

drupal/recipes/wunder_base/config/field.field.node.article.field_excerpt.yml, drupal/recipes/wunder_pages/config/core.entity_form_display.node.frontpage.default.yml, drupal/recipes/wunder_pages/config/core.entity_form_display.node.page.default.yml, drupal/recipes/wunder_pages/config/core.entity_view_display.node.frontpage.default.yml, drupal/recipes/wunder_pages/config/core.entity_view_display.node.frontpage.teaser.yml, drupal/recipes/wunder_pages/config/core.entity_view_display.node.page.default.yml, drupal/recipes/wunder_pages/config/core.entity_view_display.node.page.teaser.yml, drupal/recipes/wunder_pages/config/field.field.node.frontpage.field_excerpt.yml, drupal/recipes/wunder_pages/config/field.field.node.frontpage.field_image.yml, drupal/recipes/wunder_pages/config/field.field.node.page.field_excerpt.yml, drupal/recipes/wunder_pages/config/field.field.node.page.field_image.yml
https://wunder.atlassian.net/browse/NEX-65
- Improve the description of Excerpt field so that editors understand it's used for Search and Metatags also. 
- Add image fields to Frontpage and Page so that they will be used in the og:image and search. 
*Link to feature environment:*
https://feature-nex-65-next.next4drupal-project.dev.wdr.io/
=> NEX-65: Add image fields to Page and Frontpage, and improve descriptions for Excerpt fields.

next/components/user-menu.tsx, next/public/locales/en/common.json, next/public/locales/fi/common.json, next/public/locales/sv/common.json
=> Prevent header items styles breaking just above mobile breakpoint

next/lib/contexts/language-links-context.tsx, next/pages/all-articles/[[...page]].tsx
Currently, for next-only pages, when switching languages the user is taken to the homepage for that language: 
1. user is on `/all-articles`
2. user switches to Swedish using the language selector
3. user is taken to `/sv`
This PR changes this so that the user is taken to `sv/all-articles`
This needs to be applied manually to each page, and has these limitations: 
1. The path of the page needs to be hard-coded, because in the context of `getStaticProps` we can't know the path of the page (as weird as it feels, this seems to be the case)
2. We cannot add this for the `/search` page, because switching languages does not refresh the search results, and so the user would get an inconsistent UI. So for the search page, switching languages will take people to the frontpage.
So this PR adds this …
=> NEX-77: Language links for next-only pages

next/lib/zod/paragraph.ts, next/wunder-component-library/accordion.tsx
This PR fixes a mismatch between Drupal settings for the accordion and its Zod schema.
1. pick an existing page with an accordion, edit it, remove the accordion title, save the page
2. the page should still display correctly
Example on Silta feature branch:
Drupal: https://feature-nex-81.next4drupal-project.dev.wdr.io/en/node/17/edit
Next: https://feature-nex-81-next.next4drupal-project.dev.wdr.io/en/media-and-publishing
=> NEX-82: Allow the heading of the accordion to be empty

silta/silta-storybook.yml
No ticket, 1-line fix.
- Use `text/javascript` instead of legacy `application/javascript`
*How to test:*
1. Check that Storybook still loads.
*Reasoning:*
https://datatracker.ietf.org/doc/rfc9239/
- Better align with current standards
- `text/javascript` is now the only "proper" mimetype for JavaScript files
- other types such as `application/javascript` alias to `text/javascript`
- Avoid magical thinking
- If someone looking at silta-storybook.yml doesn't know about RFC9239, they might think that there has been some good reason to use specifically `application/javascript` for .mjs
- This could cause them to start always setting that mimetype for .mjs or even all .js, without knowing why it's done or what is affected by doing so (= magical thinking)
=> Use supported mimetype for .mjs

drupal/recipes/wunder_next_setup/config/user.role.next_api_role.yml
* this fixes errors when viewing past revisions links.
There is one complication though, when viewing a past revision of the PAGE content type, that has paragraphs, the paragraphs are shown at their _current_ revision. (I think it's a limitation of jsonapi + paragraphs)
So in practice this is not really useful for content with paragraphs.
This works nicely!
Paragraphs are shown at their last version in any case, making what is shown misleading for users:
=> NEX-90: Add missing permissions to the next_api role to view all revisions

drupal/composer.json
With "vanilla" drupal core, when you request a node with paragraphs at a specified revision via JSONApi, the paragraphs will be returned at their most recent version. This is a problem for us here, because when a content editor clicks on a revision, they expect to see the node (and its paragraph) as they were at that point in history.
As suggested on https://github.com/chapter-three/next-drupal/issues/509 , we are now adding this patch:
* more info at: https://www.drupal.org/project/drupal/issues/3088239#comment-14708895
That seems to solve the problem nicely:
To test:
1. pick a page
2. edit the page, add an edit to a paragraph content (for example, add text like in the screenshot)
3. visit the "Revisions" tab
4. view the node at the original revision: you should not see the change that …
=> NEX-90: Add patch to show paragraphs at correct revision when showing preview of a node revision

next/components/formatted-text.tsx
* Ensure nested elements are handled with the same options as top level elements
Before this change, elements within for example a <p> tag were parsed without any option specified. This caused for example nested images not to be correctly transformed into Next.js image components.
=> NEX-89: Fix for html parsing in wysiwyg areas

next/pages/api/articles-listing.ts
https://wunder.atlassian.net/browse/NEX-93 
We have a listing that gets its data client-side, and we are using zod to validate the elements in the response. If any element does not pass validation, the array will have an item with `null`  as a value.
This is a problem for the frontend, and it can crash the site. This fix prevents it by filtering out the offending items from the array before it's returned.
Not too easy to test in silta, but locally you can try messing with the data, see that the article is filtered out:
=> NEX-93: Filter out null values when retrieving latest articles for client side listing

README.md, drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_base/config/simple_sitemap.bundle_settings.default.node.article.yml, drupal/recipes/wunder_base/config/simple_sitemap.custom_links.default.yml, drupal/recipes/wunder_base/config/simple_sitemap.settings.yml, drupal/recipes/wunder_base/config/simple_sitemap.sitemap.default.yml, drupal/recipes/wunder_base/config/simple_sitemap.sitemap.index.yml, drupal/recipes/wunder_base/config/simple_sitemap.type.default_hreflang.yml, drupal/recipes/wunder_base/config/simple_sitemap.type.index.yml, drupal/recipes/wunder_base/recipe.yml, drupal/recipes/wunder_pages/config/simple_sitemap.bundle_settings.default.node.page.yml, drupal/web/modules/custom/wunder_sitemap/src/SitemapExporter.php, drupal/web/modules/custom/wunder_sitemap/wunder_sitemap.info.yml, drupal/web/modules/custom/wunder_sitemap/wunder_sitemap.module, drupal/web/modules/custom/wunder_sitemap/wunder_sitemap.services.yml, drupal/web/sites/default/settings.php, silta/silta-next.yml
https://feature-nex-94-next.next4drupal.dev.wdr.io/sitemap.xml 
This feature branch adds a xml sitemap to the template.
It works like this:
* we add the `simple_sitemap` module to Drupal, and configure it so that:
* the sitemap is created in a single file
* the sitemap includes `article` and `page` content types only
* the sitemap uses the base url of the frontend to generate the links instead of the backend base url
* we add a custom drupal module that exports the sitemap into an actual xml file to the files directory at each cron run
* we add a rewrite to the frontend part of the silta setup, so that if a visitor visits the `/sitemap.xml` path on the frontend, the browser will be served the contents of the xml file from drupal's file directory.  
1. create a new content
2. run cron on …
=> NEX-94: xml sitemap

next/next.config.js, silta/silta-next.yml
This Pr switches to next rewrites instead of silta redirects for the proxying of the sitemap.
This makes it simpler and more generic.
=> NEX-94: Move the proxying for the sitemap from silta to next rewrites

drupal/composer.json, drupal/recipes/wunder_next_setup/config/redirect.settings.yml
This PR fixes the limitation that we saw in this previous PR around multilingual redirects: https://github.com/wunderio/next4drupal-project/pull/30
We were already using a patch for the decoupled router module, the latest version fixes the issue: https://www.drupal.org/project/decoupled_router/issues/3111456
Before this last version of the patch, if a redirect was found for a language, the calculated path returned to the frontend did not take into consideration the language requested. This patch fixes it, so we can reactivate the automatic creation of redirects when a path is updated. Since paths are tied to titles, this is very common.
1. rebuild the environment if testing locally using the big command
1. log into the backend
1. pick a content item, visit it on the frontend, take note of …
=> NEX-38: Support multilingual redirects, activate automatic creation of redirects when aliases are updated.

drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_next_setup/recipe.yml, drupal/web/modules/custom/wunder_next/wunder_next.module
We used to have a custom hook to assign automatically a role to users that registered trough the site. Now the `registration_role` module has a proper d10 release, so we can remove our custom code and use the contrib module instead.
=> NEX-106: Remove our custom hook to assign role on register, use the proper registration_role module

drupal/recipes/wunder_next_setup/config/registration_role.setting.yml, drupal/recipes/wunder_next_setup/recipe.yml, drupal/web/modules/custom/wunder_next/wunder_next.module, drupal/web/modules/custom/wunder_next/wunder_next.tokens.inc, next/components/error-required.tsx, next/pages/api/auth/[...nextauth].ts, next/pages/api/register.ts, next/pages/auth/login.tsx, next/pages/auth/register.tsx, next/public/locales/en/common.json, next/public/locales/fi/common.json, next/public/locales/sv/common.json
This PR improves the workflow for user registration and resetting of the password:
1. validation of register and login form
2. add token for the frontend login url
3. add email messages with the token to direct users to the frontend site
4. add redirects to the frontend after a password is chosen or reset
5. add messages to the user in the frontend regarding the various operations
6. add redirect to dashboard after logging in after password has been reset
Easier to show in a video: 
https://github.com/wunderio/next4drupal-project/assets/185412/06fe7bfa-b82b-4932-a053-e65cb54dd794
=> NEX-110: Improvements for registration and logging in

.lando.yml, drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_search/config/elasticsearch_helper.settings.yml, drupal/web/modules/custom/wunder_search/src/Controller/WunderSearchController.php, drupal/web/modules/custom/wunder_search/src/Plugin/ElasticsearchIndex/MultilingualContentIndex.php, next/pages/api/search.ts, silta/elasticsearch.Dockerfile
Elasticsearch 7 will stop being supported relatively soon, so this PR updates the template to elasticsearch 8.
These are the changes:
* new version of elasticsearch in Lando and Silta setups
* update to elasticsearch_helper version 8.x
* adjustments to our custom module, due to new version of elasticsearch client php library
* improvement to the client side code
run the megacommand (including lando rebuild) , wait, see if search works
https://feature-nex-113-next.next4drupal.dev.wdr.io/search?size=n_20_n&filters%5B0%5D%5Bfield%5D=content_type&filters%5B0%5D%5Bvalues%5D%5B0%5D=Article&filters%5B0%5D%5Btype%5D=all
=> NEX-116: Update to Elasticsearch 8

drupal/recipes/wunder_next_setup/config/simple_oauth.settings.yml, next/pages/api/auth/[...nextauth].ts
Before, the token was set to expire each 300 seconds, and the session in frontend was using the default value in next-auth, which is 30 days. 
This meant that it was likely to have a situation where the user was logged into the frontend, but the site used an expired token when doing calls to the backend.
both are now set to 5 days.
I think we should still investigate how to improve how the session is handled (for example checking it periodically and logging the user out if the token is expired and cannot be renewed etc), but this should be an improvement already.
=> Sync drupal token expiration time, and session validity in frontend

.circleci/config.yml, silta/nginx.Dockerfile
This PR updates the silta setup according to the instructions posted at https://github.com/wunderio/silta/releases/tag/2023-10-03
I have changed the nginx dockerfile definition only, since we are using specially defined images for all other dockerfils.
=> Update the silta definitions for silta1.0

.circleci/config.yml, silta/node.Dockerfile, silta/php.Dockerfile, silta/shell.Dockerfile
This means the Docker images would be updated with the latest fixes. Related to Jānis' comment in slack [here](https://wunder.slack.com/archives/C8UN6AG9W/p1696507963658529?thread_ts=1696500393.268959&cid=C8UN6AG9W)
=> Use silta v1 major tags for docker images

README.md
Currently the big command leaves the background node server running, and this can be confusing for first time users, that will need to run `lando npm-stop` to stop it, and are left without instructions.
In this PR we improve the command by: 
* stopping the background server operation after content has been imported into drupal via the migration
* provide better information to the terminal
* starting the server in production mode, giving also the alternative link to the frontend. The developer can then stop the server with control-c as usual, and nothing is running in the background
* small tweaks to the readme file
The terminal will show this output at the end of the big command:
=> NEX-119: Improvements for the big command to setup the template

drupal/package-lock.json
Updated: 
json5 -> 1.0.2
nanoid -> 3.3.6
semver -> 7.5.4
postcss -> 8.4.31
word-wrap -> 1.2.5
yaml -> 2.3.3
=> Update frontend dependencies according to npm audit

next/.eslintignore
This PR adds a `.eslintignore` file to tell eslint to not look into node_modules, .next, etc.
`lando npm run lint`  would hang (or, take forever)
`lando npm run lint` should take a reasonable time.
=> Add an .eslintignore file to exclude some directories from eslint.

next/components/header/user-menu.tsx, next/lib/auth/redirect-expired-login.ts, next/pages/api/auth/[...nextauth].ts, next/pages/auth/login.tsx, next/pages/dashboard/index.tsx, next/pages/dashboard/webforms/[webformName]/[webformSubmissionUuid].tsx, next/public/locales/en/common.json, next/public/locales/fi/common.json, next/public/locales/sv/common.json
https://wunder.atlassian.net/browse/FAIS-44
Previously, if a logged in user's session expired, it was problematic because the frontend didn't "react" to it properly. If a logged-in user's session expired and they tried to access a protected route, they would be kicked to the frontpage (always in English), but the UI in the header would still show their username and give no indication that they aren't actually logged in anymore. The only way to resolve it was for the user to guess that logging out and back in would solve the problem.
This PR improves the situation like so:
If a logged-in user with an expired access token tries to visit `/dashboard`, which is a protected route, they are instead redirected to the `/auth/login` page in the correct language. Additionally, a new query param …
=> NEX-118: Improve handling of expired login sessions

next/lib/zod/menu.ts
- Set "attributes" property as optional -> without this change, a menu item that does not have "attributes" set will break the site.
- Add "external" property to MenuItem schema
Example menu item with both `attributes` and `external`:
```
{
"type": "menu_link_content--menu_link_content",
"id": "menu_link_content:6c12ce5c-7d2b-4b5f-96ab-e993296986bb",
"description": null,
"enabled": true,
"expanded": false,
"menu_name": "main",
"meta": {
"entity_id": "18"
},
"options": {
"attributes": {
"icon": "twitter"
},
"external": true
},
"parent": "",
"provider": "menu_link_content",
"route": {
"name": "",
"parameters": []
},
"title": "Example external link",
"url": "https://www.google.com",
"weight": 0,
"langcode": "en"
}
```
=> NEX-125: Update MenuItem types

drupal/recipes/wunder_base/config/editor.editor.basic_html.yml, drupal/recipes/wunder_base/config/editor.editor.full_html.yml, drupal/recipes/wunder_base/config/field.field.node.article.field_image.yml, drupal/recipes/wunder_base/config/filter.format.basic_html.yml, drupal/recipes/wunder_base/config/filter.format.full_html.yml, drupal/recipes/wunder_base/config/filter.format.restricted_html.yml, drupal/recipes/wunder_media/config/field.field.media.image.field_media_image.yml
Too big images can crash the site, this branch limits to: 
2500 x 2500 
and  5 megabytes. 
Larger images will be resized.
This applies to: 
- image in article
- image in media item
- images added to wysiwyg fields.
=> NEX-128: Add limits for images in pixel size and megabyte size 

next/lib/zod/frontpage.ts, next/lib/zod/page.ts
Improve paragraphs filtering performance by changing
```js
.filter(Boolean)
```
to simple null check function
```js
.filter((paragraph: any): boolean => paragraph != null)
```
Benchmarked to be around ~39% faster on 2-level nested paragraphs data, likely more with deeper nesting.
1. Check that front page and page content still load properly
=> Improve paragraphs filtering performance

.circleci/config.yml
https://wunder.atlassian.net/browse/NEX-134
Fix the logic generating the special NEXT_DOMAIN and DRUPAL_DOMAIN env var values. This removes the mismatch between expected and actual domain values in case of a long branch names (which happens quite often) as those get truncated due to length limitation and a hash suffix is appended.
This solution was found by @k4lv15 for another project.
=> NEX-134: Fix problem with deployments and long branch names

.circleci/config.yml
https://wunder.atlassian.net/browse/NEX-134 
https://app.circleci.com/pipelines/github/wunderio/next-drupal-starterkit?branch=feature%2FNEX-134-follow-up
This is a followup for #174 fixing some additional edge cases discovered in another project where expected and actual domains still didn't match.
=> NEX-134: Truncate release names only if 36 or more characters long

Changelog.md, drupal/composer.json, drupal/composer.lock, drupal/recipes/wunder_next_setup/config/graphql_compose.settings.yml, next/lib/gql/graphql.ts
* update to latest version of graphql_compose https://www.drupal.org/project/graphql_compose/releases/2.1.0-beta1
* switch to using entity ids instead of uuids, since we need the id in the response to render a specific version of the node in preview mode
=> Update to graphql_compose 2.1 beta1, fix preview of revisions

drupal/web/sites/default/settings.php
Reverts wunderio/next-drupal-starterkit#184
This PR was meant to fix an issue with lando 3.21 where the memory limit was dropped to 128m, but in v3.21.0-beta.4 the limit is set back to -1.
=> Revert "NEX-121: Prevent lando memory limit errors during local development"

drupal/web/modules/custom/wunder_next/wunder_next.module
We have seen that content editors might be tempted to change the path of the frontpage nodes from the pathauto default `frontpage-[language]`. 
This causes issues, so this small PR overrides the node edit form for frontpage nodes, making sure that the default value cannot be changed, and adds a small explanation text, explaining why it's needed.
=> NEX-140:  Add form_alter to prevent content editors to change the path of frontpage nodes.

next/pages/[...slug].tsx, next/pages/index.tsx
When returning a 404 in pages that are generated using ISR, you should add a revalidate.
In this branch, we add 10 seconds for frontpage (since it's more critical) and the same 60 seconds for any page
=> Add relalidate when returning a 404 for slug and frontpage

drupal/composer.json, drupal/composer.lock, drupal/patches/recipe-10.2.x.patch, drupal/recipes/wunder_base/recipe.yml, next/components/media/media--document.tsx, next/lib/drupal/absolute-url.ts, next/pages/[...slug].tsx, silta/silta.yml
This branch adds updates and fixes for core and contrib
1. fix security issue with registration_role https://www.drupal.org/sa-contrib-2024-015 
2. update to drupal 10.2.4 and drush 12. For this we also needed to update the recipes patch
3. add patch for paragraphs 1.17 when used with 10.2.4 https://www.drupal.org/node/3425348
4. turn the 10.2 core patch for recipes into a local patch
5. fix issue with links in media component
6. fix getStaticPaths (paths had double language)
=> NEX-142: Update to drush 12, drupal 10.2.4 + misc fixes

drupal/web/modules/custom/wunder_sitemap/src/SitemapExporter.php, drupal/web/modules/custom/wunder_sitemap/wunder_sitemap.info.yml, drupal/web/modules/custom/wunder_sitemap/wunder_sitemap.services.yml, next/next.config.js, silta/silta.yml
In order to serve the sitemap at [frontend]/sitemap.xml , we: 
1. export the sitemap to a file in `public//siltemap.xml`
2. add a rewrite to next.js proxying /sitemap.xml to [drupal]/site/default/files/sitemap.xml
The current code in `wunder_sitemap` can result in the sitemap.xml file that gets exported to be deleted, since it's not registered as a drupal file.
With the changes in this PR:
* now the file will be an actual file entity with a usage, and so it won't be removed by cron.
* the file won't be replaced if the sitemap is empty
With this change, once you run cron, you should see this entry in the list of files:
=> Improve service used to export the sitemap to a file

next/next.config.js, silta/node.Dockerfile
In this PR: 
* set the  [standalone option](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files) for `npm run build` when in CI
* adapt the dockerfile to copy the needed directories in the right place, and switch to the minimal `server.js` script to run the site 
This gives us: 
1. smaller docker image size
2. quicker build ( before: 1m 35s, after: 32s)
should be greener!
1. on silta the site should still work: https://standalone-next.next-drupal-starterkit.dev.wdr.io
2. locally, nothing should change, you can still use `npm run build` and then `npm run start`
=> NEX-144: Switch to standalone next build in CI, adapt the dockerfile

.lando.yml, drupal/web/modules/custom/wunder_democontent/src/EventSubscriber/WunderDemocontentRevalidateSubscriber.php, drupal/web/modules/custom/wunder_democontent/wunder_democontent.services.yml, next/next.config.js, setup.sh, silta/silta.yml
Now that we added #193 , our build in silta for the main environment started failing.
The reason is that we run the migration included in `wunder_democontent` after deployment, which in turn tries to call the frontend for revalidation. This won't work, because the frontend will either not exist or have a different secret
So this pr adds a mechanism to prevent revalidation while the migration runs.
This is done with an event subscriber set to a higher priority than what the `next` module provides, which will stop the propagation of the event if a state variable is set. We set that variable during the build in silta, then we unset it.
Also, I added a couple of other small things: 
1. I removed the proxy elasticsearch in lando (gave an error, does not really do much)
2. we were checking for …
=> NEX-147: Do not revalidate in silta when building the template

next/pages/[...slug].tsx
https://feature-frontpage-redirect-051.next-drupal-starterkit.dev.wdr.io/
- If a user visits e.g. /fi/frontpage-fi, redirect to /fi instead of showing duplicate content under the /frontpage-fi url
Compare the behaviour of affected urls between main environment and this one, e.g.:
- https://next-drupal-starterkit.dev.wdr.io/frontpage-en to https://feature-frontpage-redirect-051.next-drupal-starterkit.dev.wdr.io/frontpage-en
- https://next-drupal-starterkit.dev.wdr.io/fi/frontpage-fi to https://feature-frontpage-redirect-051.next-drupal-starterkit.dev.wdr.io/fi/frontpage-fi
=> If a catch-all route loads a frontpage node, redirect to / in the correct locale

next/lib/contexts/language-links-context.tsx, next/pages/[...slug].tsx
Currently the recent changes in #205 assume that all node types are set up for translations.
This might not be the case, and currently the site will break, expecting all content types to have a `translations` property. this PR fixes that, allowing the node not to have that property and still be rendered.
The language links will just be the standard ones.
=> Support rendering nodes that are not set up to be translatable

next/pages/[...slug].tsx
https://wunder.atlassian.net/browse/NEX-145
We have setup the [..slug].tsx page to handle redirects: if the route corresponds to a redirect we do a redirect in next.js
However, so far we were always returning a temporary redirect (which for next.js means `307` response status). In drupal you are able to set the response code (the most common being 301). 
So in this PR we map status codes in Drupal to response codes in next.js like this: 
`302`, `307` -> `permanent: false`
all others -> `permanent: true`
=> NEX-152: Return permanent or temporary redirect based on the redirect status code set on the Drupal side

next/.gitignore, next/.graphqlrc.yml, next/codegen-access-token.ts, next/codegen.ts, next/package-lock.json, next/package.json
Since https://github.com/wunderio/next-drupal-starterkit/pull/213, the graphql endpoint now requires authentication via an access token. This means we need to:
- Create and store an access token before running graphql-codegen script (322f4994ebda9209a982bbec9c5d1ccccda7caa4)
- Update graphql-codegen config to use that token (ee0b11a0c628ae2fdc220bd7e3570b999002be19)
- Expose the graphql schema so the vscode-graphql extension can use it. Though it previously fetched the schema itself, it now uses the file next/lib/graphql/schema.graphql that is generated by graphql-codegen (12b442358f2be88c43612fd4238cdda9601967b5)
Checkout this PR locally, run `lando npm install`, and `lando npm run graphql-codegen`. Everything should be working as expected, including autocomplete when editing graphl …
=> NEX-153: Add necessary authentication to graphql-codegen

next/lib/drupal/graphql-drupal-client.ts
Auth is now always required for GraphQL requests.
=> NEX-153: Remove withAuth option from Drupal client's doGraphQlRequest

silta/silta-next.yml
<details>
<summary><h3>Fix the proxy buffer size being too small by default:</h3></summary>
<p>
Since we upgraded from traefik to ingress-nginx the NextJS login hasn't been working. This fixes the proxy buffer size, so it works again. 
A Silta wide fix will be coming soon, but with this change we can have it working now. 
</p>
</details>
=> NEX-000: Increase the proxy buffer size to get NextJS login working with ingress-nginx.

next/lib/constants.ts, next/lib/contexts/language-links-context.tsx, next/lib/drupal/drupal-client.ts, next/lib/get-common-page-props.ts, next/pages/404.tsx, next/pages/500.tsx, next/pages/[...slug].tsx, next/pages/all-articles/[[...page]].tsx, next/pages/auth/login.tsx, next/pages/auth/register.tsx, next/pages/dashboard/index.tsx, next/pages/dashboard/webforms/[webformName]/[webformSubmissionUuid].tsx, next/pages/index.tsx, next/pages/search.tsx
https://wunder.atlassian.net/browse/NEX-101
https://feature-nex-101-data-fetchi4a2.next-drupal-starterkit.dev.wdr.io
See commits for more specifics, but the main parts of this are:
- Cleanup page data fetching logic in general (getStaticProps, getCommonPageProps etc)
- Encourage faster page generation by kicking off promises as soon as possible (no more waiting until all other page data has been fetched, then `await getCommonPageProps(...)` right at the end)
- Abort the build if a page is 404 during `next build` (pages returned from getStaticPaths should always exist)
- Throw an error if the graphql query for node data is unsuccessful in getStaticProps (and provide a link to CMS logs for further debugging). This means that if there are networking or GraphQL problems, the page will not 404 …
=> NEX-101: Improve data fetching and error handling

next/app/sitemap.ts, next/lib/utils.ts
Similar idea and ticket as https://github.com/wunderio/next-drupal-starterkit/pull/236 but specifically for the sitemap. Decided to do this in a separate PR to keep things a bit more manageable. That one should be merged first, and then the diff for this PR will become smaller without the unrelated changes.
https://wunder.atlassian.net/browse/NEX-101 (ticket is about improving data fetching and error handling in general)
https://feature-nex-101-sitemap-next.next-drupal-starterkit.dev.wdr.io/sitemap.xml
- 5b6b2c6247f309c020f82e00e2451103697224eb is the only relevant commit here. Improvements:
- Generate sitemaps for each locale in parallel rather than sequentially
- Fetch each page in parallel rather than sequentially (except for the first page for each locale, as we need that to know how …
=> NEX-101: Sitemap.xml improvements

drupal/composer.json, drupal/patches/graphql_compose_unpublished_translations.patch
Applies patch found at https://www.drupal.org/project/graphql_compose/issues/3464624
=> NEX-165: Add patch to graphql_compose to allow for nodes with unpublished translations

next/pages/[...slug].tsx
https://wunder.atlassian.net/browse/NEX-172 
We were not correctly passing the node id when doing the graphql query to get the entity at a certain revision. This PR fixes that.
1. edit a piece of content
2. a revision is created
3. click on the "revisions" tab
4. click on the link of the previous revision
5. the content is shown at that revision
=> NEX-172: Fix preview of previous revisions of nodes

next/components/preview-banner.tsx, next/pages/api/exit-preview.ts
[NEX-173](https://wunder.atlassian.net/browse/NEX-173)
[Next.js](https://nex-173-next.next-drupal-starterkit.dev.wdr.io/) `silta/demo`
[Drupal](https://nex-173.next-drupal-starterkit.dev.wdr.io/) `admin/admin`
Keep the developer or content editor on the current page after exiting preview mode.
Added a callback URL to the exit link in preview-banner.tsx. This callback is passed to /api/exit-preview.tsx to redirect the user back to the same page after exiting preview mode.
To improve the user experience by preventing unnecessary redirects when exiting preview mode. This ensures that developers and content editors remain on the page they were previewing, allowing them to continue their workflow without disruption.
1. Ensure both the frontend and backend environments are running.
2. Edit some …
=> NEX-173: Redirect to current page after exiting preview

.lando.yml
* This has become necessary in newer versions of lando to be able to access the drupal service from within lando using https.
(See https://github.com/lando/core/issues/229 )
=> Tell Lando node service to use the openssl CA

.lando.yml
Similar idea as https://github.com/wunderio/next-drupal-starterkit/pull/254 , but without using the NODE_OPTIONS env var.
This feels like we are using the right env var for the job.
* This has become necessary in newer versions of lando to be able to access the drupal service from within lando using https.
=> Add the NODE_EXTRA_CA_CERTS env var to the node service

next/pages/api/preview.ts
* this fixes the notice: API handler should not return a value, received object.
To test: 
1. start the server in dev mode
1. open a node in drupal's node view
2. observe that the notice "API handler should not return a value, received object." is not displayed anymore in the console
(This was fixed in another project, I am porting the fix here)
=> NEX-174: Do not return anything from the api preview route

.lando.yml
This branch adds the npx command to lando.
To test:
1. switch to this branch
2. if you were working with an app router branch before (it will delete untracked file, so be careful?) `git clean -d -f`
3. `./setup-lando.sh -c`
4. stop the server with control-c
5. cd next (the npx command will be executed in the directory you are in
6. for example: `lando npx shadcn@latest add badge`
=> NEX-175: Add the possibility of running npx commands in lando

.lando.yml
Reverts wunderio/next-drupal-starterkit#255 and wunderio/next-drupal-starterkit#254
Lando has now included similar changes: https://github.com/lando/node/commit/50b0fa7aa33bfe0df8eb1f91296a15c2a6492ee8 
So we can revert these changes. Make sure you are using the latest version of lando.
=> Revert our workaround to fix lando CA node cert issues

next/next.config.js
This ensures CDNs can serve stale page contents for one year. See links for more info:
https://www.flightcontrol.dev/blog/secret-knowledge-to-self-host-nextjs#isr--stale-while-revalidate https://focusreactive.com/configure-cdn-caching-for-self-hosted-next-js-websites/#stale-while-revalidate
=> Add swrDelta config option for CDNs

next/next.config.js
This ensures CDNs can serve stale page contents for one year. See links for more info:
https://www.flightcontrol.dev/blog/secret-knowledge-to-self-host-nextjs#isr--stale-while-revalidate https://focusreactive.com/configure-cdn-caching-for-self-hosted-next-js-websites/#stale-while-revalidate
=> Add swrDelta config option for CDNs (app router branch)

README.md, drupal/composer.json, drupal/recipes/wunder_pages/config/workflows.workflow.moderation.yml, drupal/recipes/wunder_pages/recipe.yml, drupal/web/modules/custom/wunder_democontent/migrations/nodes_pages.yml, drupal/web/modules/custom/wunder_democontent/migrations/nodes_pages_translations.yml, next/src/app/[locale]/(dynamic)/[...slug]/page.tsx, next/src/lib/drupal/get-node.ts, next/src/lib/graphql/queries.ts
This PR adds:
1. enabling of the workflows and content moderation modules
2. add patch at https://www.drupal.org/project/graphql_compose/issues/3462517 for graphl_compose to add the possibility of adding the revision to a route query
3. adapting the frontend code to pass the version in the expected way
https://github.com/user-attachments/assets/ea680c08-20b0-4631-b7ea-4213279b0bb8
1. `./setup-lando.sh -c`
2. log into the backend, edit a "page", create a draft revision, preview it at node/id
3. create a new page, save it in as a draft, you should be able to see it at node/id
=> NEX-84: Support forward revisions when displaying a revision in the node page in drupal

drupal/composer.json, drupal/composer.lock, next/package-lock.json, next/package.json, next/src/app/[locale]/(dynamic)/[...slug]/page.tsx, next/src/app/api/disable-draft/route.ts
Next-drupal 2.0 is out! https://next-drupal.org/blog/next-drupal-2-0
This pr updates the starterkit to it.
1. ./lando-setup.sh -c 
2. create pages, preview pages, log in, etc
=> NEX-185: Update to next-drupal 2.0

drupal/web/modules/custom/wunder_next/wunder_next.module
After merging #276 , we noticed that in multilingual content, the "latest revision" tab would always show the node in the default language, even if a translation existed.
https://github.com/user-attachments/assets/999083b7-3481-496c-8776-7c55f3ddf975
In this PR we fix this issue by leveraging the `_next_next_site_preview_alter` hook, checking if the entity has a translation for the active language of the site, and switching to the translation if so.
=> NEX-187: Fix issues with latest version tab and translated entities

next/.vscode/extensions.json
Versions of the [GraphQL: Language Feature Support](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) > 0.9.4 < 0.13 produced an error when used with graphql codegen.
The newly released 0.13.2 version that contains https://github.com/graphql/graphiql/pull/3861 now fixes the problem, so we can remove our comment from the `extensions.json` file. 🥳
=> Remove instructions to downgrade the graphql.vscode-graphql vscode extension
