wunderio/next-drupal-starterkit

- drupal/composer.json
- next/components/navbar.tsx
* added patch to the drupal side
* updated logic on the next side, adding a new type and functionality to filter the menu items at the navbar level
> NEX-18: Filter menu items by the active language

- next/components/media--video.tsx
- next/components/media.tsx
- next/components/paragraph--video.tsx
- next/components/paragraph.tsx
- next/lib/get-params.ts
- next/lib/utils.ts
- next/package-lock.json
- next/package.json
- next/tailwind.config.js
This PR adds: 
* the react-youtube package to display a youtube videoo
* the  aspect-ratio tailwind package for some basic responsiveness for the video
* video paragraph component
* media-video component
*[Link to ticket: NEX-21](https://wunder.atlassian.net/browse/NEX-21)*
*How to test:*
1. do the setup of the project as detailed in the README in the root of the site, and have the backend and frontend running
2. log into drupal (`lando drush uli`) 
3. create a new piece of content of type "landing page"
4. add paragraphs to it, add at least a video paragraph (you can add any youtube video, I have added this https://www.youtube.com/watch?v=R5U_WQvzcFU&feature=emb_title&ab_channel=ChapterThree 
5. visit the page at the frontend, you should be seeing the youtube video, and you should be …
> NEX-21: Add displaying of youtube video paragraphs

- next/components/divider.tsx
- next/components/footer.tsx
- next/components/formatted-text.tsx
- next/components/heading--page.tsx
- next/components/heading--paragraph.tsx
- next/components/latest-articles.tsx
- next/components/layout.tsx
- next/components/node--article--teaser.tsx
- next/components/node--article.tsx
- next/components/node--basic-page.tsx
- next/components/node--frontpage.tsx
- next/components/paragraph--text.tsx
- next/components/search/search-box-input.tsx
- next/components/search/search-result.tsx
- next/lib/contexts/language-links-context.tsx
- next/lib/get-params.ts
- next/package-lock.json
- next/package.json
- next/pages/404.tsx
- next/pages/500.tsx
- next/pages/[...slug].tsx
- next/pages/index.tsx
- next/pages/search.tsx
- next/public/locales/en/common.json
- next/public/locales/fi/common.json
- next/public/locales/sv/common.json
- next/styles/icons/arrow.svg
- next/tailwind.config.js
- next/types/index.ts
> Styling improvements etc

- next/package-lock.json
- next/package.json
This update fixes performance problems that were introduced in 3.20.
https://github.com/colinhacks/zod/releases/tag/v3.21.0
> Update Zod to 3.21.0

- drupal/composer.lock
Updates drupal to 10.0.5 version, to fix security issues: 
https://www.drupal.org/project/drupal/releases/10.0.5
> Chore: update composer.lock packages for drupal core security update

- drupal/composer.lock
Security update for drupal 10
https://www.drupal.org/project/drupal/releases/10.0.8
> NEX-53: Update to latest drupal 10 version

- silta/silta.yml
*Link to ticket: JIRA-123*
Don't import reference data on first deployment as we are anyway going to do a fresh install.
3. Validate that xyz is working.
> Disable importing reference data.

- next/components/contact-form.tsx
- next/components/footer.tsx
- next/components/formatted-text.tsx
- next/components/search/search-box-input.tsx
- next/components/search/search-multicheckbox-facet.tsx
- next/components/search/search-result.tsx
- next/package-lock.json
- next/package.json
- next/pages/404.tsx
- next/pages/500.tsx
- next/pages/auth/login.tsx
- next/pages/dashboard/index.tsx
- next/pages/dashboard/webforms/[webformName]/[webformSubmissionUuid].tsx
- next/pages/search.tsx
- next/postcss.config.js
- next/stories/badge.stories.tsx
- next/stories/input.stories.tsx
- next/styles/globals.css
- next/tailwind.config.js
- next/wunder-component-library/badge.tsx
- next/wunder-component-library/button.tsx
- next/wunder-component-library/input.tsx
- next/wunder-component-library/label.tsx
- next/wunder-component-library/status-message.tsx
- next/wunder-component-library/textarea.tsx
[Related to NEX-50: UI components from Wunder component library](https://wunder.atlassian.net/browse/NEX-50)
- add a `.hyperlink` class to style links; use it where appropriate. External links now have an icon to show they are external.
- add a Label component; use it where appropriate. Add to storybook.
- add a Badge component; use it on Search page
- improve styling (and a bit of a11y) of Search page
*How to test:*
1. Check links in different pages and contexts look good
2. Ditto for Labels
3. Check the Search page looks and performs decently on all screens
4. `lando npm i && lando npm run storybook`. Check the Input story for an example of the Label being used there (note: should we actually just group these into a "Form components" story or similar?)
6. …
> NEX-50: Style links; add Label component; Search page improvements

- next/components/article-teasers.tsx
- next/components/paragraph--accordion--one-column.tsx
- next/components/paragraph--accordion--two-columns.tsx
- next/components/paragraph--hero.tsx
- next/components/search/search-pagination.tsx
- next/lib/utils.ts
- next/package-lock.json
- next/package.json
- next/wunder-component-library/badge.tsx
- next/wunder-component-library/button.tsx
- next/wunder-component-library/checkbox.tsx
- next/wunder-component-library/divider.tsx
- next/wunder-component-library/input.tsx
- next/wunder-component-library/label.tsx
- next/wunder-component-library/modal.tsx
- next/wunder-component-library/status-message.tsx
- next/wunder-component-library/textarea.tsx
https://wunder.atlassian.net/browse/NEX-79
See commit messages.
*How to test:*
Go to https://feature-nex-79-btn-next.next4drupal.dev.wdr.io - hover styles of the buttons should now work correctly.
> NEX-79: Improve Button styling

- drupal/composer.json
- drupal/composer.lock
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.403.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.404.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.front.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.global.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.node.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.taxonomy_term.yml
- drupal/recipes/wunder_base/config/metatag.metatag_defaults.user.yml
- drupal/recipes/wunder_base/config/metatag.settings.yml
- drupal/web/modules/custom/phpunit_example/tests/src/Unit/AddClassTest.php
- drupal/web/modules/custom/wunder_democontent/migrations/users.yml
- drupal/web/modules/custom/wunder_democontent/sources/users.csv
- drupal/web/modules/custom/wunder_next/src/Commands/WunderNextCommands.php
- drupal/web/modules/custom/wunder_next/wunder_next.module
- drupal/web/modules/custom/wunder_search/src/Controller/WunderSearchController.php
- drupal/web/modules/custom/wunder_search/src/Plugin/ElasticsearchIndex/MultilingualContentIndex.php
- drupal/web/modules/custom/wunder_search/src/Plugin/Normalizer/NodeNormalizer.php
Main changes: 
* updated all contrib and core to 10.1.2
* removed patch for metatag, updated to 2.0
* added the restui module
* changed the passwords from plain text to hashed in users.csv because of https://www.drupal.org/node/3322420
To test: visit the site on silta: (wake up both if necessary)
* back https://feature-nex-92.next4drupal.dev.wdr.io/
* front https://feature-nex-92-next.next4drupal.dev.wdr.io
In my test the site works as before.
> NEX-92: Update core to 10.1.2 and contrib modules to latest available versions

- drupal/composer.json
- drupal/composer.lock
Update the following composer packages so that the template stays up to date:
drupal/core-*  to 10.1.3
drupal/json_api_extras
drupal/redirect to 1.9
drupal to 1.16
> NEX-108: Update Drupal core and available contrib modules

- drupal/composer.lock
Fixes this vulnerability: 
https://www.drupal.org/sa-core-2023-006
> NEX-114: Update Drupal core to 10.1.4

- drupal/web/sites/default/settings.php
* this can help with potential timeouts in jsonapi queries: https://www.drupal.org/project/drupal/issues/3022864
> NEX-132: Set isolation level and optimizer_search_dept properties for mariadb

- drupal/composer.lock
* includes security updates for drupal core and migration tools
> Update contrib modules to latest versions and Drupal core to 10.1.8

- next/.dockerignore
Adds a dockerignore file for the frontend part, some files only useful for local environment
> NEX-141:  Add .dockerignore file for frontend container

- next/tsconfig.json
This improves DX by revealing more of the type within e.g. VSCode and other IDEs that use TS language server features. Very handy indeed. Demo gif from another project that uses the starterkit:
> TypeScript: Enable noErrorTruncation in TS config

- drupal/web/modules/custom/wunder_next/wunder_next.module
In #215 the value for the noindex metatag was wrong, this fixes it
> NEX-154: Fix the noindex metatag

- next/package-lock.json
- next/package.json
* this solves the issue in https://github.com/chapter-three/next-drupal/issues/759
> Override the next.js dependency for next-drupal to be the same as in package.json

- drupal/web/modules/custom/wunder_next/src/Commands/WunderNextCommands.php
- drupal/web/sites/default/settings.php
- next/pages/[...slug].tsx
This PR cleans up a couple of minor things that were noticed after https://github.com/wunderio/next-drupal-starterkit/pull/213 was merged.
> NEX-153: Minor cleanup after PR#213

- next/pages/search.tsx
Drupal: https://feature-search-caching.next-drupal-starterkit.dev.wdr.io
ssh login: `ssh www-admin@feature-search-caching-shell.next-drupal-starterkit -J www-admin@ssh.dev.wdr.io`
Next: https://feature-search-caching-next.next-drupal-starterkit.dev.wdr.io/search
- Added `queryClient` from react-query to perform search requests with `queryKey` depending if the `state.searchTerm` is changing
- When the first results are returned from ES, the search state and queryKey are added to the query client
- If the searchTerm does not change, search will return cached data. If it changes, it will perform another search request
- This also works when selecting filters
[Explain what was done and why. You can also add screenshots here if it helps.]
1. With the Network tab open on the console. Try to …
> Caching Search results

- drupal/composer.json
- drupal/composer.lock
- drupal/recipes/wunder_base/config/node.type.article.yml
- drupal/recipes/wunder_base/config/taxonomy.vocabulary.tags.yml
- drupal/recipes/wunder_base/config/views.view.content.yml
- drupal/recipes/wunder_base/config/views.view.files.yml
- drupal/recipes/wunder_next_setup/config/graphql.settings.yml
- drupal/recipes/wunder_next_setup/config/require_login.settings.yml
- drupal/recipes/wunder_next_setup/config/views.view.articles.yml
- drupal/recipes/wunder_pages/config/node.type.frontpage.yml
- drupal/recipes/wunder_pages/config/node.type.page.yml
Changes:
* update to drupal 10.3.2
* 10.3 now includes the recipes feature natively, in this branch we remove the patch that we used in 10.2
* update configuration in recipes resulting from `drush updb`
Applying the recipe now shows a progress bar:
> NEX-164: Upgrade to drupal 10.3.2, update contrib modules

- drupal/composer.json
- drupal/composer.lock
This updates the graphql_compose module to the latest version, which includes this fix: https://www.drupal.org/project/graphql_compose/issues/3464624 
And this allows us to remove a patch that we added to fix translation issues in #239
> NEX-171: Upgrade the graphql_compose contrib module to version 2.2.1

- next/package-lock.json
Update next to latest version, fixes security issue.
> NEX-178: Update next.js to 14.2.21 and dependencies

- drupal/recipes/wunder_pages/config/core.entity_view_display.node.page.default.yml
> NEX-184: Fix typo in node page configuration module dependencies

- next/package-lock.json
```
lando npm i
up to date, audited 1425 packages in 982ms
found 0 vulnerabilities
```
> NEX-191: Update frontend dependencies

- drupal/composer.json
- drupal/composer.lock
[Update Drupal core 10.4.2 => 10.4.4](https://github.com/wunderio/next-drupal-starterkit/commit/0f346caed4b0a61127424b9e12ed663ca6ed8e81)
[Update contrib module elasticsearch_helper 8.1 => 8.2](https://github.com/wunderio/next-drupal-starterkit/commit/50338ad008a4ff9559a3cafd084f53436dceb3e2)
Cypress tests pass.
> NEX-192: Update backend dependencies

- next/package-lock.json
- next/package.json
Fixes: https://nextjs.org/blog/cve-2025-29927
Locally cypress tests are happy: 
```
Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✔  template.cy.ts                           00:41        8        8        -        -        - │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
✔  All specs passed!                        00:41        8        8        -        -        -  
```
> NEX-193: Update next.js 14.2.25
